FROM ruby:3.0.0

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install rubocop
RUN bundle install

COPY . .

CMD ["rails", "server", "-b", "0.0.0.0", "&&"]