version: '3'

services:

  DBpostgres:
    image: postgres
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    container_name: "DBpostgres"
    restart: always
    networks:
      - app
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - DBpostgres
    networks:
      - app
  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "80:80"
    restart: always

networks:
  app:
    driver: bridge