version: '3'

services:

  DBpostgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    container_name: "DBpostgres"
    restart: always
